name: build

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: liberica
      - run: sudo apt-get install -y makeself
      - run: ant makeself -Dtarget.arch=${{ matrix.arch }}
      - name: Rename artifact
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          FILE=$(ls out/qz-tray-*.run)
          mv "$FILE" "out/qz-tray-${VERSION}-${{ matrix.arch }}.run"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qz-tray-ubuntu-${{ matrix.arch }}
          path: out/qz-tray-*.run

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: liberica
      - run: ant pkgbuild -Dtarget.arch=${{ matrix.arch }}
      - name: Rename artifact
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          FILE=$(ls out/qz-tray-*.pkg)
          mv "$FILE" "out/qz-tray-${VERSION}-${{ matrix.arch }}.pkg"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qz-tray-macos-${{ matrix.arch }}
          path: out/qz-tray-*.pkg

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: liberica
      - run: choco install nsis
      - run: ant nsis -Dtarget.arch=${{ matrix.arch }}
      - name: Rename artifact
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          FILE=$(ls out/qz-tray-*.exe)
          mv "$FILE" "out/qz-tray-${VERSION}-${{ matrix.arch }}.exe"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qz-tray-windows-${{ matrix.arch }}
          path: out/qz-tray-*.exe

  release:
    runs-on: ubuntu-latest
    needs: [ubuntu, macos, windows]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-assets

      - name: Display collected files
        run: ls -R ./release-assets

      - name: Generate SHA256SUMS.txt
        run: |
          cd release-assets
          find . -type f ! -name "SHA256SUMS.txt" -exec sha256sum {} \; > SHA256SUMS.txt
          cat SHA256SUMS.txt

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-assets/**/*
